FROM ruby:2.3.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev apt-utils zip curl jq

#Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN apt-get update -qq && apt-get install -y nodejs

#Install yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y yarn

#Install npm
RUN apt-get npm
RUN npm install n -g

RUN mkdir /myapp
WORKDIR /myapp

# docker build -f Workspaces/dockers/Dockerfile_rails -t ruby233/myapp .
